In [3]:
import pandas as pd
df = pd.read_csv(r"C:\Users\DELL\Desktop\PROJECTS\Netflix-Movie-Recommendation\data\clean data\netflix_titles_clean.csv")

In [4]:
df.head(5)

,type,title,director,cast,country,release_year,rating,listed_in,description
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown Cast,United States,2020,PG-13,Documentaries,"As her father nears the end of his life, filmm..."
1,TV Show,Blood & Water,Unknown Director,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown Country,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,TV Show,Jailbirds New Orleans,Unknown Director,Unknown Cast,Unknown Country,2021,TV-MA,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,TV Show,Kota Factory,Unknown Director,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
df[['title',
    'listed_in',
    'description',
    'director',
    'cast',
    'country',
    'rating']]

,title,listed_in,description,director,cast,country,rating
0,Dick Johnson Is Dead,Documentaries,"As her father nears the end of his life, filmm...",Kirsten Johnson,Unknown Cast,United States,PG-13
1,Blood & Water,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",Unknown Director,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,TV-MA
2,Ganglands,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown Country,TV-MA
3,Jailbirds New Orleans,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",Unknown Director,Unknown Cast,Unknown Country,TV-MA
4,Kota Factory,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,Unknown Director,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,TV-MA
...,...,...,...,...,...,...,...
8802,Zodiac,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,R
8803,Zombie Dumb,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",Unknown Director,Unknown Cast,Unknown Country,TV-Y7
8804,Zombieland,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,R
8805,Zoom,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,PG
8806,Zubaan,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,TV-14

Select Required Columns

In [6]:
features = ['director', 'cast', 'listed_in', 'description', 'country']

for col in features:
    df[col] = df[col].fillna('')

handle missing values

In [7]:
df['tags'] = (
    df['listed_in'] + ' ' +
    df['director'] + ' ' +
    df['cast'] + ' ' +
    df['country'] + ' ' +
    df['description']
)

Create Tags Column

In [10]:
df[['title', 'tags']].head()

                   title                                               tags
0   Dick Johnson Is Dead  documentaries kirsten johnson unknown cast uni...
1          Blood & Water  international tv shows, tv dramas, tv mysterie...
2              Ganglands  crime tv shows, international tv shows, tv act...
3  Jailbirds New Orleans  docuseries, reality tv unknown director unknow...
4           Kota Factory  international tv shows, romantic tv shows, tv ...

In [11]:
import re

def clean_text(text):
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    return text

df['tags'] = df['tags'].apply(clean_text)

In [12]:
movies = df[['title', 'tags']]

In [13]:
movies.head()

                   title                                               tags
0   Dick Johnson Is Dead  documentaries kirsten johnson unknown cast uni...
1          Blood & Water  international tv shows  tv dramas  tv mysterie...
2              Ganglands  crime tv shows  international tv shows  tv act...
3  Jailbirds New Orleans  docuseries  reality tv unknown director unknow...
4           Kota Factory  international tv shows  romantic tv shows  tv ...

In [14]:
movies.shape
movies.isnull().sum()

title    0
tags     0
dtype: int64

In [ ]:
movies.sample(5)

,title,tags
6597,Detour,thrillers christopher smith tye sheridan bel ...
1866,The Legend of Bhagat Singh,dramas international movies rajkumar santoshi...
7021,Hulk Vs.,action adventure sci fi fantasy sam liu ...
3577,Better Than Us,crime tv shows international tv shows tv dra...
4827,Pacificum: Return to the Ocean,documentaries international movies mariana ts...

In [19]:
movies.to_csv(
    "../data/clean data/netflix_tags.csv",
    index=False
)

print("Feature engineered dataset saved successfully.")

Feature engineered dataset saved successfully.

In [9]:
df['tags'] = df['tags'].str.lower()

make the tags in lower case

In [18]:
movies['tags'].iloc[0]

'documentaries kirsten johnson unknown cast united states as her father nears the end of his life  filmmaker kirsten johnson stages his death in inventive and comical ways to help them both face the inevitable '

checking the one tag